# Generated by Django 4.1 on 2022-08-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('ImageUrl1', models.URLField(blank=True)),
                ('ImageUrl2', models.URLField(blank=True)),
                ('ImageUrl3', models.URLField(blank=True)),
                ('ImageUrl4', models.URLField(blank=True)),
                ('ImageUrl5', models.URLField(blank=True)),
                ('status', models.BooleanField(blank=True)),
                ('DateTimeField', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
